CREATE TABLE receipt_scans (
    id BIGINT NOT NULL AUTO_INCREMENT,
    group_id BIGINT NOT NULL,
    uploaded_by BIGINT NOT NULL,
    category_id BIGINT NULL,
    original_name VARCHAR(255) NULL,
    storage_path VARCHAR(700) NULL,
    content_type VARCHAR(100) NULL,
    file_size BIGINT NULL,
    provider VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    raw_text LONGTEXT NULL,
    merchant VARCHAR(180) NULL,
    total_amount BIGINT NULL,
    expense_date DATE NULL,
    confidence DECIMAL(5,4) NULL,
    message VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL,
    expires_at DATETIME(6) NOT NULL,
    attached_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    INDEX idx_receipt_scans_group_created (group_id, created_at),
    INDEX idx_receipt_scans_user_status (uploaded_by, status, created_at),
    CONSTRAINT fk_receipt_scans_group FOREIGN KEY (group_id) REFERENCES expense_groups(id),
    CONSTRAINT fk_receipt_scans_user FOREIGN KEY (uploaded_by) REFERENCES users(id),
    CONSTRAINT fk_receipt_scans_category FOREIGN KEY (category_id) REFERENCES categories(id)
);
